version: '3'
services:
    pfsense_backup_app:
        image: amacado/pfsense-backup-remote:latest
        environment:
            - PFSENSE_USER=backup
            - PFSENSE_PASS=backup
            - PFSENSE_IP=xxxxx
            - PFSENSE_PORT=443
            - PFSENSE_SCHEME=https
            - PFSENSE_BACK_UP_RRD_DATA=1
            - PFSENSE_CRON_SCHEDULE=4 0 * * *
            - BACKUPNAME=xxxxxx
            - GPG_NAME=xxxxxx
            - TZ=Europe/Berlin
        volumes:
            - "<path>/data:/data"
            - "<path>/xxxx.json:/gcloud/config/service-account-credentials.json"
            - "<path>/xxxx.public.asc:/gpg/config/gpg-public.asc"
